import React from "react";
import type { P1ExecutiveData } from "../types";
import { ReportPage } from "../primitives/ReportPage";
import { ReportBadge } from "../primitives/ReportBadge";

interface Props {
  data: P1ExecutiveData;
  datasetName: string;
  generatedAt: string;
}

export function P1_Cover({ data, datasetName, generatedAt }: Props) {
  return (
    <ReportPage
      pageNumber={1}
      totalPages={11}
      title="Cover Page"
      isCover={true}
      className="rpt-cover"
    >
      <div
        style={{
          display: "flex",
          flexDirection: "column",
          justifyContent: "space-between",
          height: "100%",
          padding: "40px 10px",
          color: "var(--rpt-ink)",
        }}
      >
        {/* Top Header Row */}
        <div
          style={{
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between",
            borderBottom: "1px solid var(--rpt-border)",
            paddingBottom: 20,
          }}
        >
          <div style={{ display: "flex", alignItems: "center", gap: 12 }}>
            <div
              style={{
                width: 38,
                height: 38,
                borderRadius: 8,
                background: "linear-gradient(135deg, var(--rpt-brand), var(--rpt-accent))",
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                color: "#ffffff",
                fontSize: 18,
                fontWeight: 900,
              }}
            >
              IF
            </div>
            <div>
              <div
                style={{
                  fontSize: 12,
                  fontWeight: 800,
                  letterSpacing: "0.12em",
                  textTransform: "uppercase",
                  color: "var(--rpt-brand-dark)",
                }}
              >
                InsightForge AI
              </div>
              <div
                style={{
                  fontSize: 9,
                  color: "var(--rpt-text-muted)",
                  marginTop: 2,
                }}
              >
                Enterprise Business Intelligence
              </div>
            </div>
          </div>
          <ReportBadge label="Confidential" variant="critical" dot />
        </div>

        {/* Center Hero Title */}
        <div style={{ margin: "120px 0 80px 0", position: "relative" }}>
          {/* Subtle design grid lines */}
          <div
            style={{
              position: "absolute",
              top: -40,
              left: -20,
              width: 140,
              height: 140,
              borderLeft: "2px solid var(--rpt-brand-soft)",
              borderTop: "2px solid var(--rpt-brand-soft)",
              opacity: 0.5,
              pointerEvents: "none",
            }}
          />
          
          <div
            style={{
              fontSize: 11,
              fontWeight: 800,
              letterSpacing: "0.2em",
              textTransform: "uppercase",
              color: "var(--rpt-brand)",
              marginBottom: 16,
            }}
          >
            Executive Analytics Report
          </div>
          <h1
            style={{
              fontSize: 38,
              lineHeight: 1.15,
              fontWeight: 900,
              color: "var(--rpt-brand-dark)",
              margin: 0,
              letterSpacing: "-0.02em",
            }}
          >
            {data.reportTitle || "Dataset Strategic Analysis"}
          </h1>
          <p
            style={{
              fontSize: 14,
              color: "var(--rpt-text-muted)",
              marginTop: 18,
              lineHeight: 1.6,
              maxWidth: 540,
            }}
          >
            Comprehensive diagnostic auditing, performance evaluation, trend forecasting, and prescriptive decision modeling generated by the InsightForge AI analytics engine.
          </p>
        </div>

        {/* Bottom Details Grid */}
        <div
          style={{
            background: "var(--rpt-surface2)",
            border: "1px solid var(--rpt-border)",
            borderRadius: 8,
            padding: 24,
            display: "grid",
            gridTemplateColumns: "1.2fr 1fr",
            gap: 24,
          }}
        >
          <div>
            <div style={{ marginBottom: 16 }}>
              <span
                style={{
                  display: "block",
                  fontSize: 9,
                  fontWeight: 800,
                  textTransform: "uppercase",
                  color: "var(--rpt-text-muted)",
                  letterSpacing: "0.08em",
                  marginBottom: 4,
                }}
              >
                Staged Dataset
              </span>
              <span
                style={{
                  fontSize: 13,
                  fontWeight: 700,
                  color: "var(--rpt-ink)",
                  wordBreak: "break-all",
                }}
              >
                {datasetName}
              </span>
            </div>
            <div>
              <span
                style={{
                  display: "block",
                  fontSize: 9,
                  fontWeight: 800,
                  textTransform: "uppercase",
                  color: "var(--rpt-text-muted)",
                  letterSpacing: "0.08em",
                  marginBottom: 4,
                }}
              >
                Data Volume
              </span>
              <span style={{ fontSize: 13, fontWeight: 700, color: "var(--rpt-ink)" }}>
                {data.rowCount.toLocaleString()} records / {data.columnCount} attributes
              </span>
            </div>
          </div>
          <div>
            <div style={{ marginBottom: 16 }}>
              <span
                style={{
                  display: "block",
                  fontSize: 9,
                  fontWeight: 800,
                  textTransform: "uppercase",
                  color: "var(--rpt-text-muted)",
                  letterSpacing: "0.08em",
                  marginBottom: 4,
                }}
              >
                Date Generated
              </span>
              <span style={{ fontSize: 13, fontWeight: 700, color: "var(--rpt-ink)" }}>
                {generatedAt}
              </span>
            </div>
            <div>
              <span
                style={{
                  display: "block",
                  fontSize: 9,
                  fontWeight: 800,
                  textTransform: "uppercase",
                  color: "var(--rpt-text-muted)",
                  letterSpacing: "0.08em",
                  marginBottom: 4,
                }}
              >
                Classification
              </span>
              <span style={{ fontSize: 13, fontWeight: 700, color: "var(--rpt-critical)" }}>
                Confidential - Internal Board Review
              </span>
            </div>
          </div>
        </div>

        {/* Footer Meta */}
        <div
          style={{
            display: "flex",
            justifyContent: "space-between",
            fontSize: 9,
            color: "var(--rpt-text-faint)",
            borderTop: "1px solid var(--rpt-border-light)",
            paddingTop: 16,
            marginTop: 40,
          }}
        >
          <span>Prepared For: Corporate Executives & Stakeholders</span>
          <span>© InsightForge AI. All rights reserved.</span>
        </div>
      </div>
    </ReportPage>
  );
}
